// Package docs serves the embedded HTML documentation generated from the
// project's markdown (see tools/docgen). The HTML under html/ is committed and
// regenerated by `make docs-html`; a no-drift gate (`make docs-html-check`) keeps
// the committed output in lock-step with the markdown source.
//
// The served pages are STATIC, read-only content and carry no JavaScript, so this
// handler is mounted UNCONDITIONALLY in cmd/tierd — including the #429 read-only
// public-demo mode — alongside the dashboard. There is nothing here to write and
// nothing to token-gate.
package docs

import (
	"embed"
	"io/fs"
	"net/http"
	"strings"
)

// cspHeader is the Content-Security-Policy sent with every docs response.
//
// It mirrors the dashboard's locked-down posture but is even tighter: there is NO
// script-src directive, so scripts fall through to default-src 'none' and cannot
// execute at all — the generated docs carry none (the layout adds no <script> and
// bluemonday strips any that reached a fragment; see tools/docgen). style-src
// keeps 'unsafe-inline' for the layout's embedded <style> block, and img-src
// allows self + data: URIs so an inline diagram or badge renders. base-uri 'none'
// and frame-ancestors 'none' close off <base> hijacking and clickjacking.
const cspHeader = "default-src 'none'; style-src 'unsafe-inline'; img-src 'self' data:; base-uri 'none'; frame-ancestors 'none'"

const (
	// routePrefix is the mount point (matched by cmd/tierd's mux.Handle).
	routePrefix = "/docs/"

	// indexPage is served at the bare /docs/ path — the docs index (README).
	indexPage = "README.html"

	// embedDir is the directory inside the embedded FS holding the pages.
	embedDir = "html"

	contentTypeHTML = "text/html; charset=utf-8"
)

// docsFS holds the generated documentation pages. The glob is FLAT (html/*.html);
// the generator emits a flat directory on purpose so intra-doc links collapse to
// basenames (see tools/docgen).
//
//go:embed html/*.html
var docsFS embed.FS

// Handler serves the embedded HTML documentation at /docs/.
type Handler struct{}

// New returns a new docs Handler.
func New() *Handler { return &Handler{} }

// ServeHTTP implements http.Handler. It serves the docs index at "/docs/" (and
// bare "/docs") and an individual page at "/docs/<name>.html"; every other path —
// including any attempt at a subdirectory or a non-.html asset — is a 404.
//
// Security: the page name is taken from the path AFTER routePrefix and must be a
// bare "<name>.html" with no slash, so path traversal ("/docs/../secret") and any
// nested lookup are structurally impossible before the embed lookup even runs. The
// embed.FS itself only contains the committed html/*.html files, so a lookup can
// never escape to the real filesystem. Every served response carries cspHeader and
// X-Content-Type-Options: nosniff.
func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	name := strings.TrimPrefix(r.URL.Path, routePrefix)

	switch {
	case name == "" || r.URL.Path == strings.TrimSuffix(routePrefix, "/"):
		// "/docs/" or "/docs" -> the index page.
		h.servePage(w, r, indexPage)
	case strings.Contains(name, "/") || !strings.HasSuffix(name, ".html"):
		// A nested path, a traversal attempt, or a non-page asset: not served.
		http.NotFound(w, r)
	default:
		h.servePage(w, r, name)
	}
}

// servePage writes a single embedded page by its flat name, or a 404 if the name
// is not one of the committed pages. It never reaches outside the embed.FS.
func (h *Handler) servePage(w http.ResponseWriter, r *http.Request, name string) {
	body, err := fs.ReadFile(docsFS, embedDir+"/"+name)
	if err != nil {
		// The only expected error is fs.ErrNotExist (unknown page); treat any
		// read failure the same way — a missing/unreadable page is a 404, never a
		// 500 that would leak internal detail.
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Security-Policy", cspHeader)
	w.Header().Set("Content-Type", contentTypeHTML)
	w.Header().Set("X-Content-Type-Options", "nosniff")
	_, _ = w.Write(body)
}
